# Predicting Home Prices Using Multivariate Linear Regression

In [12]:
# import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import math

### Load the dataset

In [13]:
df = pd.read_csv("hiring.csv")

### Display the initial dataframe

In [5]:
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

### Reanaming columns for easy data menipulation

In [6]:
df = df.rename(columns = {'test_score(out of 10)':'test_score', 'interview_score(out of 10)':'interview_score', 'salary($)': 'salary'})
df

  experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

# Data Preparation

## Handling Missing Values

### Calculate the median of test_score and fill missing values

In [7]:
median_test_score = math.floor(df.test_score.median())
print(f"Median Test Score: {median_test_score}")

Median Test Score: 8

### Fill missing bedroom values with the calculated median

In [8]:
pip install word2number

Requirement already satisfied: word2number in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (1.1)Note: you may need to restart the kernel to use updated packages.

In [9]:
from word2number import w2n

In [10]:
df.test_score = df.test_score.fillna(median_test_score)
df
# Now the data is prepared to train the ML Model

  experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

### Fill missing experience values with the zero since there is no data about experience we assume it as zero

### Function to convert experience strings to numbers

In [11]:
def convert_experience(val):
    try:
        # Try to convert spelled-out numbers to integers
        return w2n.word_to_num(val)
    except:
        # If the conversion fails, return NaN
        return np.nan

In [10]:
# Using a for loop to iterate over the 'experience' column and apply the function
for i in range(len(df['experience'])):
    if isinstance(df['experience'][i], str):  # Check if the value is a string
        df['experience'][i] = convert_experience(df['experience'][i])

C:\Users\Administrator\AppData\Local\Temp\ipykernel_9952\2357531849.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['experience'][i] = convert_experience(df['experience'][i])
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9952\2357531849.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['experience'][i] = convert_experience(df['experience'][i])
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9952\2357531849.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['experience'][i] = convert_experience(df['experience'][i])
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9952\2357531849.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['experience'][i] = convert_experience(df['experience'][i])
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9952\2357531849.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['experience'][i] = convert_experience(df['experience'][i])
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9952\2357531849.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['experience'][i] = convert_experience(df['experience'][i])
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9952\2357531849.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['experience'][i] = convert_experience(df['experience'][i])
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9952\2357531849.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['experience'][i] = convert_experience(df['experience'][i])
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9952\2357531849.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['experience'][i] = convert_experience(df['experience'][i])
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9952\2357531849.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['experience'][i] = convert_experience(df['experience'][i])
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9952\2357531849.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['experience'][i] = convert_experience(df['experience'][i])
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9952\2357531849.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['experience'][i] = convert_experience(df['experience'][i])

### Display the dataframe after handling missing values

In [38]:
print("DataFrame after filling missing values:")
df

DataFrame after filling missing values:

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

# Train the Multivariate Linear Regression Model

### Feature Selection and fitting the model

In [39]:
reg = linear_model.LinearRegression()
X = df[["area", "bedrooms", "age"]]
y = df["price"]
reg.fit(X, y)

LinearRegression()

### Display coefficients and intercept

In [40]:
print("Coefficients:", reg.coef_)
print("Intercept:", reg.intercept_)

Coefficients: [  112.06244194 23388.88007794 -3231.71790863]
Intercept: 221323.0018654043

# Model Equation

### The model equation can be represented as:
### y = m1 * area + m2 * bedrooms + m3 * age + b
### where:
### m1, m2, m3 = coefficients
### b = intercept

# Predicting Home Price

### Example Prediction
#### Predict the price of a home with area = 3000 sq ft, bedrooms = 3, and age = 40 years

In [41]:
predicted_price = reg.predict([[3000, 3, 40]])[0]  # Accessing the first element from the prediction
print(f"Predicted Price for a home with area 3000 sq ft, 3 bedrooms, and age 40: ${predicted_price:.2f}")

Predicted Price for a home with area 3000 sq ft, 3 bedrooms, and age 40: $498408.25

C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

# Verifying the prediction using manual calculation

In [42]:
manual_prediction = (reg.coef_[0] * 3000) + (reg.coef_[1] * 3) + (reg.coef_[2] * 40) + reg.intercept_
print(f"Manual Calculation of Predicted Price: ${manual_prediction:.2f}")

Manual Calculation of Predicted Price: $498408.25

# The model has been trained and is capable of predicting home prices based on area, bedrooms, and age.